package model;

public enum ResourceType {
	CLAY,ORE,STONE,WOOD,GLASS,LOOM,PAPYRUS,COIN,VICTORY,SHIELD,SCIENCE,COMMERCE,GUILD,
	CLAYORE,CLAYSTONE,CLAYWOOD,ORESTONE,OREWOOD,STONEWOOD,
	NUMTYPES
}
